### PR TITLE
64-bit mac binary and build files

### PR DESCRIPTION
**Pull request by whilesoftware**

### CODE REVIEW

**Comment by grapefrukt** [comment]
As far as I can see this looks good!
It'll take me a while to get to a computer, but once one materializes I'll test this and merge it in.
Thanks!

**Comment by grapefrukt** [comment]
As I'm looking at this I see that you're replacing the 32 bit lib in the documentation. Also, the Linux build will compile the 64 bit version twice. So, I can't merge this as is.

But, I totally agree that this needs doing, so either you clean up the PR or I'll look into it myself.
The problem I had when I originally did this was that I couldn't detect if it was a 32 or 64 bit build in the include.nmml, meaning that I didn't know which library file to copy over (since they're named the same and needs to go in the same folder).

**Comment by whilesoftware** [comment]
My original PR did accidentally replace the 32-bit lib

**Comment by whilesoftware** [comment]
yep, I see where I screwed that up. fixing and sending a new PR now.

**Pull request closed without merging**
